shopkitties/config/routes.rb
Rails.application.routes.draw do
  root 'items#index'


  resources :users, path: 'mon_compte'
  devise_for :users, path: ''

  resources :carts, path: 'mon_panier', only: [:show,:index] do
    resources :orders, path: 'mes_commandes', only: [:new, :create, :show]
  end


  resources :items, path: 'kitty' do
    resources :cart_items
    resources :cat_pictures
  end

end

shopkitties/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

shopkitties/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items

end

shopkitties/app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

shopkitties/app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_items
  has_one_attached :cat_picture

  validates :title, :price, :image_url, presence: true
  validates :title, length: {in: 3..20}
  validates :price, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 10000 }

  scope :filter_by_price, -> (price) { where price: price }

end

shopkitties/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
  belongs_to :user
  has_many :order_items

end

shopkitties/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

shopkitties/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, through: :cart

  belongs_to :cart, optional: true

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

shopkitties/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

shopkitties/app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def create
    @user = current_user
    @cart_id = @user.cart_id
    @cartitem = CartItem.new(cart_id: @cart_id, item_id: params[:item_id])
    if @cartitem.save
      redirect_to items_path
    else end
  end

  def index
  end

  def show

  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    respond_to do |format|
      format.html { }
      format.js { }
    end
  end
end

shopkitties/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]


  def create
    @cart = Cart.create
  end

  def show

    @cart_id = current_user.cart_id

    @user_cart= []
    CartItem.all.each do |item|
       if item.cart_id == @cart_id
        @user_cart << item
       end
      end

    @amount=0
    @user_cart.each{|i|
      @amount = @amount + i.item.price
      }
  end

  def update
  end

  def edit
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    respond_to do |format|
      format.html { }
      format.js { }
    end
  end

end

shopkitties/app/controllers/cat_pictures_controller.rb
class CatPicturesController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @item.cat_picture.attach(params[:cat_picture])
    redirect_to(item_path(@item))
  end
end

shopkitties/app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    if user_signed_in?
      @user = current_user
      if @user.cart_id == nil
        Cart.create()
        @user.update(cart_id: Cart.last.id)
      else end
    else end
      if search 
    else end 
end

  def show
    @item = Item.find(params[:id])
  end

  def search
    @parameter = params[:search]
    @results = Item.all.where("lower(title) LIKE :search", search: @parameter)
  end 
  
end

shopkitties/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @user = current_user
    @cart_id = Cart.find(params[:cart_id]).id

    @user_cart= []
    CartItem.all.each do |item|
       if item.cart_id == @cart_id
        @user_cart << item
       end
      end
    # Amount in cents
    @amount=0
    @user_cart.each{|i|
      @amount = @amount + i.item.price
    }
  end

  def create
    @cart_id = Cart.find(params[:cart_id]).id
    @user_cart= []
    CartItem.all.each do |item|
       if item.cart_id == @cart_id
        @user_cart << item
       end
      end
    @amount=0
    @user_cart.each{|i|
      @amount = @amount + i.item.price}

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: (@amount*100).to_i,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })

    @order = Order.new(user_id: current_user.id, cart_id: @cart_id)
    @order.save


    @user_cart.each{ |cart_item|
      @order_item = OrderItem.new(item_id: cart_item.item_id, order_id: Order.last.id)
      @order_item.save}

    OrderMailer.confirmation_email(current_user).deliver


    CartItem.where(cart_id: @cart_id).destroy_all

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to cart_path(@cart_id)
    end
end

shopkitties/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def new
  end

  def create
  end

  def index
  end

  def show
    @user = current_user
    @cart_id=@user.cart_id

    @orders=[]
    Order.all.each{|order|
      if order.cart_id == @cart_id
        @orders << order
      else end}

    @order_items= []
    OrderItem.all.each do |order_item|
       if order_item.order.cart_id == @cart_id
        @order_items << order_item
       end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path,
      notice: "Votre profil a été mis à jour"
    else
      render :new,
      notice: "Il y a une erreur, recommence"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
  end

  private

  def user_params

    params.require(:user).permit(:first_name, :last_name, :description)

  end

end

shopkitties/app/helpers/application_helper.rb
module ApplicationHelper
  def confirmation_email(user)

    @user = user
  
    @cart_id = @user.cart
  
    @order_array = []
    @order_items = OrderItem.all.each do |item|
        @order_array << item
    end
  
    mail(to: @user.email, subject: 'Votre commande Shopkitties')
  
    end
end

shopkitties/app/helpers/cart_items_helper.rb
module CartItemsHelper
end

shopkitties/app/helpers/carts_helper.rb
module CartsHelper
end

shopkitties/app/helpers/items_helper.rb
module ItemsHelper
end

shopkitties/app/helpers/orders_helper.rb
module OrdersHelper
end

shopkitties/app/helpers/users_helper.rb
module UsersHelper
end

shopkitties/app/views/cart_items/destroy.html.erb
<h1>CartItems#destroy</h1>
<p>Find me in app/views/cart_items/destroy.html.erb</p>

shopkitties/app/views/cart_items/index.html.erb
<h1>CartItems#index</h1>
<p>Find me in app/views/cart_items/index.html.erb</p>

shopkitties/app/views/cart_items/show.html.erb
<h1>CartItems#show</h1>
<p>Find me in app/views/cart_items/show.html.erb</p>

shopkitties/app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

shopkitties/app/views/carts/destroy.js.erb
document.querySelector("#cat-item-<%= i.item.id %>").style.display="none";

document.querySelector(".child").style.display="none";

shopkitties/app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

shopkitties/app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

shopkitties/app/views/carts/show.html.erb
<div class="container col-lg-6 card mt-5 mb-5">
    <h1 class="card-header text-center">Panier</h1>

        <ul class="list-group bg-light mb-2 mt-2">
            <% total = 0%>
            <% @user_cart.each do |i|%>
        <li class="list-group-item d-flex justify-content-between align-items-center" id="cat-item-<%= i.item.id %>">
            <%= link_to i.item.title, item_path(i.item.id) %>  <%= i.item.price%> €
            
            <% total = total + i.item.price %>


            <div class ="">
                <%= link_to item_cart_item_path(i.item.id,i.id), class: "text-danger font-weight-normal", method:"delete", remote: true do%>
                <i class="fas fa-trash-alt"></i>
                <% end %>
            </div>

           <% end %>
        </li>
          <h5 class="bg-light text-right pr-5 mt-3"> Total = <%= total%> €</h5>
          <%= render 'orders/new' %>
        </ul>
</div>

shopkitties/app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>

shopkitties/app/views/items/_search.html.erb
<h3>Résultat de recherche</h3>  

<div class="container mt-3 mb-3">
    <div class="row justify-content-between align-items-center mx-auto">
        <% @results.each do |item| %>
            <div class="col-lg-3 col-md-6 mb-2">
                <div class="card mx-auto">
                <%if item.cat_picture.attached?%>
                        <%= image_tag item.cat_picture, alt: 'cat_picture', class:"img-thumbnail", style:"height:200px; object-fit:cover;" %>
                    <%else%>
                        <p>=== Il n'y a pas encore d'image ===</p>
                    <%end%>
                <div class="card-body p-3">
                    <p class="card-title my-1"><b><%= item.title %></b></p>
                    <%= link_to "Voir plus", item_path(item.id), class: "btn btn-info btn-block" %>
                </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
<h3>Continuer à parcourir les autres photos </h3>  

<br>

shopkitties/app/views/items/index.html.erb
<div class="container mt-3 mb-5">

	<% if params[:search].blank? %>
	<% else %>
	<%= render "items/search" %>
	<% end %>

		<div class="row justify-content-between align-items-center mx-auto">
			<% Item.all.each do |item| %>
				<div class="col-lg-3 col-md-6 mb-4">
					<div class="card mx-auto">
					<%if item.cat_picture.attached?%>
							<%= image_tag item.cat_picture, alt: 'cat_picture', class:"img-thumbnail", style:"height:200px; object-fit:cover;" %>
						<%else%>
							<p>=== Il n'y a pas encore d'image ===</p>
						<%end%>
					<div class="card-body p-3">
						<p class="card-title my-1"><b><%= item.title %></b></p>
						<%= link_to "Voir plus", item_path(item.id), class: "btn btn-info btn-block" %>
					</div>
					</div>
				</div>
			<% end %>
		</div>

</div>

shopkitties/app/views/items/show.html.erb
<div class="container m-5">
    <div class="row">
        <div class="col-lg-5 col-md-12 m-auto">
          <%if @item.cat_picture.attached?%>
              <%= image_tag @item.cat_picture, alt: 'cat_picture', class:"img-thumbnail" %>
            <%else%>
              <p>=== Il n'y a pas encore d'image ===</p>
            <%end%>
        </div>
        <div class="bg-light col-lg-5 col-md-12 border p-5" style="line-height:3em">
            <h1 class="text-center"> <%= @item.title %></h1>
            <br>

            <p> <%= @item.description %></p>
            <div class="text-center font-weight-bold">
            <p><u> Prix : <%= @item.price%> €</u></p>
            <% if user_signed_in? %>
              <%= link_to 'Ajouter au panier', item_cart_items_path(params[:id]), class:"btn btn-lg btn-primary align-bottom", method: 'post' %>
              <br><br>
                <% if current_user.email == "shopkitties@yopmail.com" %>
                <h6>Uploader/Changer l'image ?</h6>
                  <%= form_tag item_cat_pictures_path(@item), multipart: true do %>
                    <%= file_field_tag :cat_picture %>
                    <%= submit_tag "mettre à jour" %>
                  <% end %>
                <% else end %>
              <% else %>
              <p>Vous devez avoir un compte pour ajouter des articles à votre panier ! </p>
              <%= link_to 'Se connecter', new_user_session_path, class: "btn btn-lg btn-secondary align-bottom" %>
              <%= link_to 'S\'inscrire', new_user_registration_path, class: "btn btn-lg btn-secondary align-bottom"%>
              </div>
              <% end %>
        </div>
        </div>
    </div>
</div>

shopkitties/app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="footer font-small special-color-dark mt-5 pt-3 bg-secondary cover">

  <!-- Footer Elements -->
  <div >
      
    <!-- Social buttons -->

      <div class="row">
        <div class="col-4" style="text-align: left;">
          <p class="ml-2 text-left text-muted">Equipe Toulouse :</p>
          <p class="ml-3 text-left text-muted">Nathan Chateau, Amy Mcarthur, Hadrien Samouillan et Xuan Wang</p>
        </div>
        <div class="col-1"></div>
        <div>
          <p class="text-muted" style="margin-top: 30px; margin-left: 100px;">SHOPKITTIES<sup>©</sup> 2020</p>
        </div>
    </div>
    <ul class="list-unstyled list-inline text-center mb-0">    

      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1">
          <i class="fab fa-2x fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1">
          <i class="fab fa-2x fa-twitter"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-gplus mx-1">
          <i class="fab fa-2x fa-google-plus-g"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-li mx-1">
          <i class="fab fa-2x fa-linkedin-in"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-dribbble mx-1">
          <i class="fab fa-2x fa-dribbble"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->
  </div>
</footer>
<!-- Footer -->

shopkitties/app/views/layouts/_jumbotron.html.erb
<div class="jumbotron jumbotron-fluid ml-1 mt-1" style="background-image: url(https://images.pexels.com/photos/127027/pexels-photo-127027.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260); background-size: 100%;height:400px; background-position:center 30%;">
  <div class="container">
    <h1 class="display-4 text-light">ShopKitties</h1>
    <p class="lead text-light">Mettez les plus belles photos de chatons dans votre panier, et partez avec !</p>
  </div>
</div>

shopkitties/app/views/layouts/_littlejumbotron.html.erb
<div class=" m-1 border" style="background-image: url(https://static.lexpress.fr/medias_10521/w_2048,h_890,c_crop,x_0,y_372/w_960,h_540,c_fill,g_north/v1558088348/grumpy-cat-2_5387055.jpg); background-size: 23%;height:160px; cover; no-repeat;">
    <div class="container" style="background-color: rgba(255, 255, 255, 0.2); margin-top: 30px; border-radius: 15px; height: 100px">
      <h1 class="display-1 text-grey text-center">SHOPKITTIES</h1>
    </div>
  </div>

shopkitties/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-primary ml-1">
   <%= link_to 'Shop Kitties', items_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Accueil', items_path, class: 'nav-link'%>
      </li>
      <li class="nav-item active">
        <% if user_signed_in? %>
        <%= link_to 'Panier', cart_path(current_user.cart_id), class: 'nav-link'%>
        <%end%>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Compte</a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>

            <%= link_to "Mon profil", user_path(current_user.id), class: 'dropdown-item'  %>

            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>

          <% else %>

            <%= link_to "Se connecter", new_user_session_path, class: 'dropdown-item'  %>

            <%= link_to "S'inscrire", new_user_registration_path, class: 'dropdown-item'  %>

        <% end %>
        </div>
        </li>
    </ul>
   <div class="nav-item mr-2 text-white"> Trouve un chaton en tapant son nom : </div> 
      <%= form_tag(items_path, method: "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Ex. psyduck", class: "form-control" %>  
    <div class="input-group-btn">
      <%= button_tag "", class: "btn btn-info       fas fa-search",:name => nil%> 

    </div>  
  </div>  
<% end %>
    </form>
  </div>
</nav>

shopkitties/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop Kitties</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/f1d8fe4e09.js" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render 'layouts/jumbotron' %>

    <%= render 'layouts/navbar' %>

    <%= yield %>

    <%= render 'layouts/footer' %>

  </body>
</html>

shopkitties/app/views/orders/_new.html.erb
<div class="container text-center mb-5 mt-5">
  <%= form_tag cart_orders_path(params[:id]) do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Nouvelle commande"
            data-email=<%=current_user.email%>
            data-amount="<%=(@amount*100)%>"
            data-currency= 'eur',
            data-locale="auto"></script>
</div>
<% end %>

shopkitties/app/views/orders/create.html.erb
<div class="container text-center mt-5 mb-5">
  <h2>Merci <%= current_user.email %>, vous avez payé <strong><%= @amount %> €</strong>!</h2>
  <div class="row mb-5 mt-5">
    <div class="col-2">

    </div>
    <div class="col-4 text-center">
      <%= link_to "Retourner à l'accueil", items_path, class: 'btn btn-success' %>
    </div>
    <div class="col-4 text-center">
      <%= link_to "Mon compte", user_path(current_user.id), class: 'btn btn-info' %>
    </div>
    <div class="col-2">

    </div>

  </div>
</div>

shopkitties/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

shopkitties/app/views/users/edit.html.erb
<div class="container mt-5 form-group">

    <div class= "bg-light container fieldset mt-3 mr3 pt-3 fieldset col-lg-4 ">
    
        <h1 class="text-center">Modifier vos informations</h1>
        <p class="border-bottom">
        
      
        <%= form_for @user do |f| %>
        
            <%= f.text_field :first_name, class: "form-control", placeholder: "Prénom" %>
            
            <br>

             <%= f.text_field :last_name, class: "form-control", placeholder: "Nom"  %>

            <br>

             <%= f.text_area :description, class: "form-control", placeholder: "Description"  %>
            
            <br>
              
            <div class="form-group text-center">

                <button type="submit" class=" float-right btn btn-success">Appliquer</button>

           </div>

         <% end %>

        <h3>Changer d'avatar ?</h3>

            <%= form_tag user_avatars_path(@user), multipart: true do %>

            <%= file_field_tag :avatar %>

            <%= submit_tag "mettre à jour" %>
            
        <% end %>

    </div>
</div>

shopkitties/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

shopkitties/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

shopkitties/app/views/users/show.html.erb
<div class="container mt-5 mb-5 offset-2">

  <div class="row">
    <div class="col-md-4">
      <div class="card mt-5">
        <h3 class="card-header">Mes informations</h3>
        <div class="card-body">
          <h5 class="card-title">Pseudo : </h5>
          <h5 class="card-title">Email : <%= current_user.email %></h5>
        </div>

        <div>
        <%= button_to "Modifier email/mot de passe", edit_user_registration_path, class: 'btn btn-warning mb-3 ml-3', method: 'get' %>
        </div>

        <div class="card-footer text-muted text-center">
          Merci de nous faire la confiance!!
        </div>
      </div>
  	</div>

    <div class="col-md-6">
      <h3 class="text-center">Mes commandes</h3>

        <% @orders.each do |order| %>
        <div class="card mb-3">
          <h5 class="card-header">Commande n° : <%= order.id %></h5>

        <% total = 0 %>
            <h5 class="ml-2"><u>Produits :</u> </h5>
          <% @order_items.each do |order_item| %>
            <div>
              <% if order_item.order_id == order.id %>
                <p class="ml-4"> <%= order_item.item.title %></p>
                <% total = total + order_item.item.price  %>
              <% end %>
            </div>
              <% end %>
              <h5 class="text-right mr-3">Prix total : <%= total  %> €</h5>
          </div>
          <%end%>
  	  </div>

  </div>
</div>

shopkitties/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>